// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO app.messages (customer_id, type, direction, status)
VALUES ($1, $2::app.message_type, $3::app.message_direction, $4::app.message_status)
RETURNING message_id, customer_id, type, direction, status
`

type CreateMessageParams struct {
	CustomerID uuid.UUID           `db:"customer_id" json:"customerId"`
	Type       AppMessageType      `db:"type" json:"type"`
	Direction  AppMessageDirection `db:"direction" json:"direction"`
	Status     AppMessageStatus    `db:"status" json:"status"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (AppMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.CustomerID,
		arg.Type,
		arg.Direction,
		arg.Status,
	)
	var i AppMessage
	err := row.Scan(
		&i.MessageID,
		&i.CustomerID,
		&i.Type,
		&i.Direction,
		&i.Status,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM app.messages WHERE message_id = $1::uuid
`

func (q *Queries) DeleteMessage(ctx context.Context, messageID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, messageID)
	return err
}

const getMessagesByCustomer = `-- name: GetMessagesByCustomer :many
SELECT message_id, customer_id, type, direction, status FROM app.messages WHERE customer_id = $1 ORDER BY message_id DESC
`

func (q *Queries) GetMessagesByCustomer(ctx context.Context, customerID uuid.UUID) ([]AppMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMessage
	for rows.Next() {
		var i AppMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.CustomerID,
			&i.Type,
			&i.Direction,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT message_id, customer_id, type, direction, status FROM app.messages ORDER BY message_id DESC
`

func (q *Queries) ListMessages(ctx context.Context) ([]AppMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMessage
	for rows.Next() {
		var i AppMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.CustomerID,
			&i.Type,
			&i.Direction,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE app.messages
SET type = $1::app.message_type, direction = $2::app.message_direction, status = $3::app.message_status
WHERE message_id = $4::uuid
RETURNING message_id, customer_id, type, direction, status
`

type UpdateMessageParams struct {
	Type      AppMessageType      `db:"type" json:"type"`
	Direction AppMessageDirection `db:"direction" json:"direction"`
	Status    AppMessageStatus    `db:"status" json:"status"`
	MessageID uuid.UUID           `db:"message_id" json:"messageId"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (AppMessage, error) {
	row := q.db.QueryRowContext(ctx, updateMessage,
		arg.Type,
		arg.Direction,
		arg.Status,
		arg.MessageID,
	)
	var i AppMessage
	err := row.Scan(
		&i.MessageID,
		&i.CustomerID,
		&i.Type,
		&i.Direction,
		&i.Status,
	)
	return i, err
}
