// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AppAccessLog struct {
	LogID      int64          `db:"log_id" json:"logId"`
	CustomerID int64          `db:"customer_id" json:"customerId"`
	UnitID     int64          `db:"unit_id" json:"unitId"`
	Datetime   time.Time      `db:"datetime" json:"datetime"`
	Action     sql.NullString `db:"action" json:"action"`
}

type AppAgreement struct {
	AgreementID int64          `db:"agreement_id" json:"agreementId"`
	CustomerID  int64          `db:"customer_id" json:"customerId"`
	UnitID      int64          `db:"unit_id" json:"unitId"`
	StartDate   time.Time      `db:"start_date" json:"startDate"`
	EndDate     sql.NullTime   `db:"end_date" json:"endDate"`
	Status      sql.NullString `db:"status" json:"status"`
}

type AppContact struct {
	ContactID   int64          `db:"contact_id" json:"contactId"`
	CustomerID  int64          `db:"customer_id" json:"customerId"`
	FirstName   sql.NullString `db:"first_name" json:"firstName"`
	LastName    sql.NullString `db:"last_name" json:"lastName"`
	Email       sql.NullString `db:"email" json:"email"`
	PhoneMobile sql.NullString `db:"phone_mobile" json:"phoneMobile"`
	PhoneHome   sql.NullString `db:"phone_home" json:"phoneHome"`
	PhoneWork   sql.NullString `db:"phone_work" json:"phoneWork"`
	Role        sql.NullString `db:"role" json:"role"`
	IsPrimary   sql.NullBool   `db:"is_primary" json:"isPrimary"`
}

type AppCustomer struct {
	CustomerID   int64     `db:"customer_id" json:"customerId"`
	CustomerName string    `db:"customer_name" json:"customerName"`
	CreatedAt    time.Time `db:"created_at" json:"createdAt"`
	IsEnabled    bool      `db:"is_enabled" json:"isEnabled"`
}

type AppCustomerAccess struct {
	AccessID      int64          `db:"access_id" json:"accessId"`
	CustomerID    int64          `db:"customer_id" json:"customerId"`
	Pin           sql.NullString `db:"pin" json:"pin"`
	AlwaysAllowed sql.NullBool   `db:"always_allowed" json:"alwaysAllowed"`
	TimeZone      sql.NullString `db:"time_zone" json:"timeZone"`
}

type AppCustomerAddress struct {
	AddressID  int64          `db:"address_id" json:"addressId"`
	CustomerID int64          `db:"customer_id" json:"customerId"`
	Type       string         `db:"type" json:"type"`
	Line1      sql.NullString `db:"line1" json:"line1"`
	Suburb     sql.NullString `db:"suburb" json:"suburb"`
	City       sql.NullString `db:"city" json:"city"`
	State      sql.NullString `db:"state" json:"state"`
	Postcode   sql.NullString `db:"postcode" json:"postcode"`
	Country    sql.NullString `db:"country" json:"country"`
	Latitude   sql.NullString `db:"latitude" json:"latitude"`
	Longitude  sql.NullString `db:"longitude" json:"longitude"`
}

type AppCustomerCustomField struct {
	FieldID    int64          `db:"field_id" json:"fieldId"`
	CustomerID int64          `db:"customer_id" json:"customerId"`
	FieldName  string         `db:"field_name" json:"fieldName"`
	FieldValue sql.NullString `db:"field_value" json:"fieldValue"`
}

type AppFacility struct {
	FacilityID int64           `db:"facility_id" json:"facilityId"`
	Name       string          `db:"name" json:"name"`
	Address    sql.NullString  `db:"address" json:"address"`
	Region     sql.NullString  `db:"region" json:"region"`
	Config     json.RawMessage `db:"config" json:"config"`
}

type AppInvoice struct {
	InvoiceID   int64          `db:"invoice_id" json:"invoiceId"`
	AgreementID int64          `db:"agreement_id" json:"agreementId"`
	DueDate     time.Time      `db:"due_date" json:"dueDate"`
	Amount      string         `db:"amount" json:"amount"`
	Status      sql.NullString `db:"status" json:"status"`
}

type AppMessage struct {
	MessageID  int64          `db:"message_id" json:"messageId"`
	CustomerID int64          `db:"customer_id" json:"customerId"`
	Type       sql.NullString `db:"type" json:"type"`
	Direction  sql.NullString `db:"direction" json:"direction"`
	Status     sql.NullString `db:"status" json:"status"`
}

type AppPayment struct {
	PaymentID  int64          `db:"payment_id" json:"paymentId"`
	InvoiceID  int64          `db:"invoice_id" json:"invoiceId"`
	Method     sql.NullString `db:"method" json:"method"`
	GatewayRef sql.NullString `db:"gateway_ref" json:"gatewayRef"`
	Status     sql.NullString `db:"status" json:"status"`
}

type AppUnit struct {
	UnitID     int64          `db:"unit_id" json:"unitId"`
	FacilityID int64          `db:"facility_id" json:"facilityId"`
	UnitType   sql.NullString `db:"unit_type" json:"unitType"`
	Size       sql.NullString `db:"size" json:"size"`
	Price      sql.NullString `db:"price" json:"price"`
	Status     sql.NullString `db:"status" json:"status"`
}
