// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AppAccessLog struct {
	LogID      int64          `db:"log_id" json:"logId"`
	CustomerID int64          `db:"customer_id" json:"customerId"`
	UnitID     int64          `db:"unit_id" json:"unitId"`
	Datetime   time.Time      `db:"datetime" json:"datetime"`
	Action     sql.NullString `db:"action" json:"action"`
}

type AppAgreement struct {
	AgreementID int64          `db:"agreement_id" json:"agreementId"`
	CustomerID  int64          `db:"customer_id" json:"customerId"`
	UnitID      int64          `db:"unit_id" json:"unitId"`
	StartDate   time.Time      `db:"start_date" json:"startDate"`
	EndDate     sql.NullTime   `db:"end_date" json:"endDate"`
	Status      sql.NullString `db:"status" json:"status"`
}

type AppCustomer struct {
	CustomerID         int64          `db:"customer_id" json:"customerId"`
	Name               string         `db:"name" json:"name"`
	ContactInfo        sql.NullString `db:"contact_info" json:"contactInfo"`
	VerificationStatus sql.NullString `db:"verification_status" json:"verificationStatus"`
	CreatedAt          time.Time      `db:"created_at" json:"createdAt"`
	IsEnabled          bool           `db:"is_enabled" json:"isEnabled"`
}

type AppFacility struct {
	FacilityID int64           `db:"facility_id" json:"facilityId"`
	Name       string          `db:"name" json:"name"`
	Address    sql.NullString  `db:"address" json:"address"`
	Region     sql.NullString  `db:"region" json:"region"`
	Config     json.RawMessage `db:"config" json:"config"`
}

type AppInvoice struct {
	InvoiceID   int64          `db:"invoice_id" json:"invoiceId"`
	AgreementID int64          `db:"agreement_id" json:"agreementId"`
	DueDate     time.Time      `db:"due_date" json:"dueDate"`
	Amount      string         `db:"amount" json:"amount"`
	Status      sql.NullString `db:"status" json:"status"`
}

type AppMessage struct {
	MessageID  int64          `db:"message_id" json:"messageId"`
	CustomerID int64          `db:"customer_id" json:"customerId"`
	Type       sql.NullString `db:"type" json:"type"`
	Direction  sql.NullString `db:"direction" json:"direction"`
	Status     sql.NullString `db:"status" json:"status"`
}

type AppPayment struct {
	PaymentID  int64          `db:"payment_id" json:"paymentId"`
	InvoiceID  int64          `db:"invoice_id" json:"invoiceId"`
	Method     sql.NullString `db:"method" json:"method"`
	GatewayRef sql.NullString `db:"gateway_ref" json:"gatewayRef"`
	Status     sql.NullString `db:"status" json:"status"`
}

type AppUnit struct {
	UnitID     int64          `db:"unit_id" json:"unitId"`
	FacilityID int64          `db:"facility_id" json:"facilityId"`
	UnitType   sql.NullString `db:"unit_type" json:"unitType"`
	Size       sql.NullString `db:"size" json:"size"`
	Price      sql.NullString `db:"price" json:"price"`
	Status     sql.NullString `db:"status" json:"status"`
}
